-- Supabase schema for the Spotify clone (run in the Supabase SQL editor).

-- Public profile for each auth user.
create table if not exists public.users (
  id uuid references auth.users not null primary key,
  full_name text,
  avatar_url text,
  billing_address jsonb,
  payment_method jsonb
);
alter table public.users enable row level security;
create policy "Users can view own data" on public.users for select using (auth.uid() = id);
create policy "Users can update own data" on public.users for update using (auth.uid() = id);

-- Create a profile row whenever someone signs up.
create or replace function public.handle_new_user() returns trigger as $$
begin
  insert into public.users (id, full_name, avatar_url)
  values (new.id, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url');
  return new;
end;
$$ language plpgsql security definer;
create or replace trigger on_auth_user_created
  after insert on auth.users for each row execute procedure public.handle_new_user();

-- Songs uploaded by users (files live in the "songs" and "images" storage buckets).
create table if not exists public.songs (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  title text,
  author text,
  song_path text,
  image_path text,
  user_id uuid references auth.users
);
alter table public.songs enable row level security;
create policy "Songs are public" on public.songs for select using (true);
create policy "Users can upload songs" on public.songs for insert with check (auth.uid() = user_id);

-- Liked songs per user.
create table if not exists public.liked_songs (
  user_id uuid references auth.users not null,
  song_id bigint references public.songs on delete cascade not null,
  created_at timestamptz not null default now(),
  primary key (user_id, song_id)
);
alter table public.liked_songs enable row level security;
create policy "Users see own likes" on public.liked_songs for select using (auth.uid() = user_id);
create policy "Users add own likes" on public.liked_songs for insert with check (auth.uid() = user_id);
create policy "Users remove own likes" on public.liked_songs for delete using (auth.uid() = user_id);

-- Storage buckets: public read, authenticated upload.
insert into storage.buckets (id, name, public) values ('songs', 'songs', true), ('images', 'images', true)
  on conflict (id) do nothing;
create policy "Public read" on storage.objects for select using (bucket_id in ('songs', 'images'));
create policy "Authenticated upload" on storage.objects for insert to authenticated with check (bucket_id in ('songs', 'images'));
